### ISSUE TITLE
raspberri pi root problem with ubuntu mate

### ISSUE THREAD

**Issue by cpfarher** [lroguet/rpi-home-assistant#2]
Hello, I have a problem when I try to configure gpio switch of rpi, getting this error when run docker rpi-home-assistant on rpi 3 with ubuntu mate installed:

`ERROR:homeassistant.components.switch:Error while setting up platform rpi_gpio
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 98, in _setup_platform
    discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/rpi_gpio.py", line 28, in setup_platform
    switches.append(RPiGPIOSwitch(name, port, invert_logic))
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/rpi_gpio.py", line 41, in __init__
    rpi_gpio.setup_output(self._port)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/rpi_gpio.py", line 39, in setup_output
    GPIO.setup(port, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!
`
It is some tricky because docker run as root...

so....It is necessary to map /dev/mem into container?

I checked that user is root inside docker container..

**Comment by lroguet** [comment]
Hi,

Not sure the issue is related to lroguet/rpi-home-assistant really.
Found some guidance @ http://blog.hypriot.com/post/docker-sensor-fu-on-a-raspberry-pi/ and yes, it looks like you'd need to add some more (`--device /dev/mem:/dev/mem`) to your `docker run` command.
